spring:
    profiles:
        active: dev
    application:
        name: "CrossPlatform"
        version: "0.1"
---
spring:
    config:
        activate:
            on-profile: dev
server:
    port: 8080
---
spring:
    config:
        activate:
            on-profile: production
server:
    port: 9001
---
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/studends_db
        username: postgres
        password: ${pass}
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
---
jwt:
    secret: ${scrt}
    access:
        duration:
            minutes: 5
            seconds: 300
        cookie-name: access-token
    refresh:
        duration:
            days: 7
            seconds: 604800
        cookie-name: refresh-token
---
logging:
    level:
        root: INFO
        com.example.demo: DEBUG
    file:
        name: logs/application.log
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %level - %msg%n"
---
spring:
    servlet:
        multipart:
            location: uploads/
            max-file-size: 10MB
            max-request-size: 10MB
            enabled: true
---
telegram:
    bot:
        name: ${chnm}
        token: ${tkn}
        chat-id: ${chat-id}
---
report:
    template-location: classpath:templates/report-templates.xlsx
---
springdoc:
    api-docs:
        path: /v3/api-docs
        enabled: true
    swagger-ui:
        path: /swagger-ui
        enabled: true
        tags-sorter: alpha
        operations-sorter: method
        display-request-duration: true
        default-model-expand-depth: 2
        default-models-expand-depth: 2
        try-it-out-enabled: true
    show-actuator: false
    packages-to-scan: com.example.crossPlatform.controller